import type { Metadata } from "next";
import localFont from "next/font/local";
import "./styles/globals.css";
import { ApolloWrapper } from "@/lib/components/ApolloWrapper";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSideBar } from "@/components/AppSideBar/AppSideBar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ApolloWrapper>
          <SidebarProvider>
            <AppSideBar />

            <main>
              <SidebarTrigger />
              {children}
            </main>
          </SidebarProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
}
